apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: bookstore
data:
  MONGO_INITDB_DATABASE: "book-store"
  SPRING_DATA_MONGODB_URI: "mongodb://mongo-service:27017/book-store"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"

