version: "3"

services:
  # MongoDB service
  mongo-db:
    image: "mongo"
    container_name: "mongo2023_lab"
    environment:
      - MONGO_INITDB_DATABASE=book-store
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # Application service
  bookstore-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookstore_app
    ports:
      - "8080:8080"
    depends_on:
      - mongo-db
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo-db:27017/book-store

volumes:
  mongo-data:
