apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: bookstore
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: S0RldkFkbWlu # base64 encoded KIIIadmin
  MONGO_INITDB_ROOT_PASSWORD: bWFydGluMTIz # base64 encoded martin123

